### ISSUE TITLE
Submodules making forking really hard

### ISSUE THREAD

**Issue by CADbloke** [Developer-Autodesk/AutoCAD.io#2]
See http://somethingsinistral.net/blog/git-submodules-are-probably-not-the-answer/ and a whole host of articles at https://www.google.com.au/search?q=git+submodule+multiple+remotes - most of which say something along the lines of "don't do it"

I appreciate that having this central repo does make it really easy to get them all but it is a major hurdle to ...
>We'd be grateful if you'd submit any enhancements or bugfixes you make for any of our samples back to the appropriate repository.

...because forking a repo means you set your own repo as `origin` and the https://github.com/Developer-Autodesk.. remote as `upstream` or something along those lines. Subrepos make that really, really, hard, hence the [Google search]( https://www.google.com.au/search?q=git+submodule+multiple+remotes) above.

http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/ may be an alternative but I feel you may get more forks and involvement by simplifying things, perhaps listing the repos as individual links, grouped by Language or something like that.

Just wanted to let you know about this barrier.

cheers
Eweb

**Comment by cyrillef** [comment]
Hi Eweb

I simply agree. Actually, this repo is obsolete and will go away very soon (2 weeks time)
All the AutoCAD.IO are today in this [organization](https://github.com/Developer-Autodesk), but will move to a new AutoCAD.IO organization as well fairly soon. GitHub is good in keeping the 'old' names, so your forks, etc.. will continue to work after move and renames. We want to have one organization per API/product - and keep meaningful names vs these odds name we got today.

Thx again for your feedback
- cyrille
